name: validprot
channels:
  - defaults
  - conda-forge
  - plotly
dependencies:
  - biopython
  - autopep8
  - matplotlib
  - numpy
  - pandas
  - python
  - pip
  - scikit-learn
  - python-kaleido
  - joblib
  - sphinx
  - plotly
  - pip:
      - duckdb
      - sphinx
      - sphinx-rtd-theme
      - pyhmmer
      - pylint
